// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Prisma CLI (migrate, db pull, studio) connects here. It must NOT be the
  // transaction pooler (DATABASE_URL, Supabase port 6543): migrations hang
  // on it. Prefer the session pooler / direct connection. The app's runtime
  // client uses DATABASE_URL separately (src/lib/prisma.ts).
  datasource: {
    url: process.env["MIGRATE_DATABASE_URL"] || process.env["DIRECT_DATABASE_URL"] || process.env["DATABASE_URL"],
  },
});
